---
# handlers file for mapr-kafka

- name: restart nfs server
  sudo_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name nfs -nodes {{ansible_fqdn}}

- name: restart kafka
  sudo_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name kafka -filter csvc==kafka
  run_once: true

